### PR TITLE
Allow calling methods of components and their features.

### LINKED ISSUE #98: How to access grid features via the angular 2 wrapper
The ignite grid has a lot of functionality available via jQuery, how can we access these interfaces via the angular 2 wrappers?
An example would be the following:

<code>$("#grid1").igGridUpdating("updateRow", 0, { Name: "Maria" });</code>

Thanks, Jon.

### PR DESCRIPTION
**Pull request by MayaKirova**
Allow calling methods of components and their features.

Closes #98

### CODE REVIEW

**Comment by kdinev** [comment]
@mpavlinov @MayaKirova Any idea why I'm not seeing the checks in the PR?

**Comment by kdinev** [comment]
@mpavlinov @MayaKirova I figured it out. Somebody had changed the branch protection. Any ideas who did that?

**Comment by mpavlinov** [comment]
@kdinev I created the branch, but didn't configure anything for the protection. I guess it used the default protection.

**Comment by kdinev** [comment]
@mpavlinov I was turned off for `master`, not for this branch.

**Pull request merged**
