### PR TITLE
Add AoT support

### PR DESCRIPTION
**Pull request by dkamburov**
#133

### CODE REVIEW

**Comment by kdinev** [comment]
@mpavlinov I would like one more person to test this on their environment.

**Comment by mpavlinov** [comment]
Ok. I'll test it.

**Comment by kdinev** [comment]
@mpavlinov Did you manage to test it?

**Comment by mpavlinov** [comment]
@dkamburov In the Readme.md the importing of the Ignite UI css files is not described. The ` replace` plugin should be better descried (include the import statement).

**Comment by mpavlinov** [comment]
I tested the AOT support and it looks good.

**Pull request merged**
