### PR TITLE
Update typescript definitions with fix for bug 235827.

### PR DESCRIPTION
**Pull request by skrustev**

### CODE REVIEW

**Comment by kdinev** [comment]
@skrustev Could you also take care of #156?

**Comment by kdinev** [comment]
@skrustev Are you going to take care of it with this PR?

**Comment by skrustev** [comment]
This PR is not related to that issue. The #156 issue is related to moving the definitions to DefinitelyTyped which should have pull request with the fixes for the 235827 bug.

**Comment by kdinev** [comment]
@skrustev Yeah, and according to #156 the files with the types should be removed from the repository. Aren't you updating one of the files that should be removed?

**Comment by kdinev** [comment]
@skrustev Deyan removed the typings and closed the issue. Now you see that there is a conflict because this file no longer exists.

**Comment by skrustev** [comment]
Ok, then you can close this PR. The changes are already present in the @types from this pull request:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19700

**Comment by kdinev** [comment]
@skrustev OK, closing this one.

**Pull request closed without merging**
